Lint/UnusedMethodArgument:
  Exclude:
    - 'lib/atlas/peering/proxy.rb'

Lint/Void:
  Exclude:
    - 'lib/atlas/client.rb'

Style/RaiseArgs:
  EnforcedStyle: compact

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 132

Metrics/CyclomaticComplexity:
  Max: 7
