#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  lib = File.expand_path('../lib', __dir__)
 
  $LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
  require 'atlas'
rescue StandardError => e
  raise("We can not handle this LOAD_PATH properly(#{e.message})")
end

Process.setproctitle('atlas_peering_ctl')
Atlas::Peering.start(ARGV)
