#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'atlas'

Process.setproctitle('atlas_peering_ctl')
Atlas::CLI.run(ARGV)
